apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-service
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 0.6Gi
    limits:
      cpu: 1000m
      memory: 0.6Gi

  rabbitmq:
    additionalConfig: |
      log.console.level = debug
      channel_max = 1700
      default_user= guest
      default_pass = guest
      default_user_tags.administrator = true
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbit-service
# spec:
#   selector:
#     app.kubernetes.io/name: rabbitmq
#     app.kubernetes.io/instance: rabbit-service
#   ports:
#     - name: amqp
#       protocol: TCP
#       port: 5672
#       targetPort: 5672
#       nodePort: 30072
#     - name: management
#       protocol: TCP
#       port: 15672
#       targetPort: 15672
#       nodePort: 31672
#   type: NodePort
