apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
  labels:
    app: tickets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
        - name: tickets
          image: jihengharbi/jihen-tickets:latest 
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://ticket-mongo-service:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: "amqp://ticketuser:user@rabbit-service.default.svc.cluster.local:5672"
              #value: "amqp://guest:guest@rabbit-service:5672"


