apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-service
  namespace: default
spec:
  replicas: 1
  persistence:
    storage: 1Gi
    storageClassName: standard
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
